function  [data, acqRatio] = extractTBN(fpath)

% USAGE: extractTBN
% DESCRIPTION: reads .tbn data generated by Turbo-SM64.  
% INPUTS: folder (folder path of .tbn file for particular experiment),
%   trial (name of experimental trial)
% OUTPUTS: data (exported .tbn data) DOES NOT WORK
% CONTACT: Rodrigo Gonzales-Rojas (rag13@rice.edu or 
%   rodrigogonzrojas@gmail.com)
% CREATED: July 22, 2021 (Not functional)
% Updates:
% Feb 21, 2022 -- Corrected errors preventing function from working, and 
% simplified code. - Renan

    % turbo resource: http://www.redshirtimaging.com/support/Turbo-SM.html
    

    % reads .tbn file as "short integer" (as described in Turbo-SM64
    %   user manual), which in MATLAB is 'int16' (alternatively, 'short' 
    %   may be used).  Then indexes the first
    %   two values in this vector.  Value #1 is the number of channels,
    %   and value #2 is the BNC-to-camera ratio
    fileID = fopen(fpath);
    header = fread(fileID,2,'int16'); % Obtain header data.

    nChannels = abs(header(1)); % Number of channels. Note: header value is negative for National Instruments system.
    acqRatio = header(2); % Ratio of BNC acquisition to imaging frame acquisition.
    
    % reads .tbn file as float64 format 
    data = fread(fileID,'float64'); % Starts reading after header because header was read above.
    data = reshape(data,length(data)/nChannels, nChannels);
    fclose(fileID);
    
end