function trimData = trimRHS(untrimData,t,frames,IntanRate)

% USAGE: trimRHS
% DESCRIPTION: relatively short function that identifies and removes
%   additional Intan recording signals added to .rhs files.  Intan will
%   automatically add additional nerve signal data before and after the
%   start of the recording, and this function filters that out so the
%   nerve signal can be aligned with the VSD signals
% INPUTS: untrimData (raw .rhs file generated by function 
%   "read_Intan_RHS2000_file" in driver), t (total time points in
%   raw .rhs file), frames (total number of frames recorded in VSD
%   experiment), IntanRate (Intan recording rate in kHz)
% OUTPUTS: trimData (.rhs data with additional frames before and after
%   experiment removed)
% CONTACT: Rodrigo Gonzales-Rojas (rag13@rice.edu or 
%   rodrigogonzrojas@gmail.com)
% LAST MODIFIED: July 22, 2021

    % identifies starting point of data (denoted as t=0) and trims off
    %   that value and all values below it in untrimData.  Then trims
    %   off excess, denoted as the number of frames acquired for VSD
    %   (frames) times the rate the Intan system records at (in kHz)
    [~,Index] = intersect(t,0);
    untrimData(:,1:Index) = [];
    trimData = untrimData(:,1:frames*IntanRate);

end